package org.nette.latte.lexer;

import com.intellij.lexer.FlexAdapter;
import com.intellij.lexer.Lexer;
import com.intellij.lexer.MergingLexerAdapter;
import com.intellij.psi.tree.TokenSet;
import org.nette.latte.psi.LatteTypes;

/**
 * Adapter for {@link LatteTopLexer} which is generated by JFlex to IntelliJ's interface
 * {@link Lexer}.
 *
 * Also merges any sequence of selected tokens to a single token.
 */
public class LattePhpLexerAdapter extends MergingLexerAdapter {
	public LattePhpLexerAdapter() {
		super(
			new FlexAdapter(new LattePhpLexer((java.io.Reader) null)),
			TokenSet.create(LatteTypes.T_TEXT, LatteTypes.T_HTML_CLOSE_TAG_OPEN, LatteTypes.T_HTML_OPEN_TAG_OPEN, LatteTypes.T_HTML_OPEN_TAG_CLOSE, LatteTypes.T_HTML_TAG_CLOSE)
		);
	}
}
